version: '3.9'
volumes:
  pgdata:
  static_files:
services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_DB: "smart_home"
      POSTGRES_USER: "admin1"
      POSTGRES_PASSWORD: "admin1pwd"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U admin1 -d smart_home']
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - ./backend:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./backend/logs:/var/log
  backend:
    build: .
    depends_on:
      - postgresdb
    env_file:
      - ./backend/.env
    volumes:
      - static_files:/app/docker-compose-project/static
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_files:/var/www/html/static
    depends_on:
      - backend

